// This file is generated by Convex.
// It is not meant to be edited directly.

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as auth from "../auth.js";
import type * as lessons from "../lessons.js";
import type * as modules from "../modules.js";
import type * as progress from "../progress.js";
import type * as quizzes from "../quizzes.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  lessons: typeof lessons;
  modules: typeof modules;
  progress: typeof progress;
  quizzes: typeof quizzes;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;